name: Notebook tests

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Test notebooks with nbmake
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.9'
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
      - name: Install PyImageJ example dependencies
        shell: bash -l {0}
        run: |
          mamba install --yes -c conda-forge pyimagej openjdk=8 pip
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[test]"
      - name: Test notebooks
        run: |
          pytest --nbmake --nbmake-timeout=3000  examples/*ipynb
